export const CAN_SIZES = ['8oz', '10oz', '11oz', '12oz', '14.9oz', '16oz', '19.2oz', '24oz', '25oz', '32oz']
export const BOTTLE_SIZES = ['7oz', '8oz', '10oz', '11.2oz', '12oz', '14.9oz', '16oz', '22oz', '24oz', '32oz', '40oz']

export const LIQUOR_UNIT_SIZE_MAP = {
  'shooter':   '50ml',
  'half pint': '200ml',
  'pint':      '375ml',
  'fifth':     '750ml',
  'liter':     '1L',
  'handle':    '1.75L',
}
export const LIQUOR_UNITS = Object.keys(LIQUOR_UNIT_SIZE_MAP)

export const PRODUCTS = [
  // Modelo
  { name: 'Modelo Especial',          type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Modelo Negra',             type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Modelo Chelada',           type: 'beer',    defaultUnit: 'can',    defaultSize: '24oz' },
  { name: 'Pacifico',                 type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  // Corona
  { name: 'Corona Extra',             type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Corona Light',             type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Corona Premier',           type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  // Heineken
  { name: 'Heineken',                 type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Heineken Silver',          type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Heineken 0.0',             type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Stella Artois
  { name: 'Stella Artois',            type: 'beer',    defaultUnit: 'bottle', defaultSize: '11.2oz' },
  // Dos Equis
  { name: 'Dos Equis Lager',          type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Dos Equis Ambar',          type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  // Tecate
  { name: 'Tecate',                   type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Tecate Light',             type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Bud family
  { name: 'Bud Light',                type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Budweiser',                type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Bud Light Platinum',       type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Coors family
  { name: 'Coors Light',              type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Coors Banquet',            type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Miller family
  { name: 'Miller Lite',              type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Miller High Life',         type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Miller Genuine Draft',     type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Michelob
  { name: 'Michelob Ultra',           type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Michelob Ultra Pure Gold', type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // Busch / PBR / misc macro
  { name: 'Busch Light',              type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Busch',                    type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'PBR',                      type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Keystone Light',           type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Natural Light',            type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Rolling Rock',             type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Yuengling Lager',          type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Yuengling Black & Tan',    type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Shiner Bock',              type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Guinness Draught',         type: 'beer',    defaultUnit: 'can',    defaultSize: '14.9oz' },
  // Craft
  { name: 'Sam Adams Boston Lager',   type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Blue Moon Belgian White',  type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Lagunitas IPA',            type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: "Lagunitas Little Sumpin'", type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Sierra Nevada Pale Ale',   type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Sierra Nevada Torpedo',    type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Sierra Nevada Hazy Little Thing', type: 'beer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Stone IPA',                type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Dogfish Head 60 Minute IPA', type: 'beer', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Founders All Day IPA',     type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Founders Centennial IPA',  type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'New Belgium Fat Tire',     type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Voodoo Ranger IPA',        type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Goose Island 312',         type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Goose Island IPA',         type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: "Bell's Two Hearted Ale",   type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: "Bell's Oberon",            type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: "Oskar Blues Dale's Pale Ale", type: 'beer', defaultUnit: 'can',   defaultSize: '12oz' },
  { name: 'Cigar City Jai Alai',      type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Deschutes Fresh Squeezed IPA', type: 'beer', defaultUnit: 'can',  defaultSize: '12oz' },
  { name: 'Firestone 805',            type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Firestone Union Jack IPA', type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Allagash White',           type: 'beer',    defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Elysian Space Dust IPA',   type: 'beer',    defaultUnit: 'can',    defaultSize: '12oz' },
  // White Claw
  { name: 'White Claw Black Cherry',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Mango',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Natural Lime',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Watermelon',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Raspberry',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Strawberry',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Tangerine',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Lemon',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Passion Fruit',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Blackberry',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Pineapple',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Peach',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Cranberry',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Ruby Grapefruit',   type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Surge Cranberry',    type: 'seltzer', defaultUnit: 'can', defaultSize: '16oz' },
  { name: 'White Claw Surge Lime',         type: 'seltzer', defaultUnit: 'can', defaultSize: '16oz' },
  { name: 'White Claw Surge Blood Orange', type: 'seltzer', defaultUnit: 'can', defaultSize: '16oz' },
  { name: 'White Claw Surge Blackberry',   type: 'seltzer', defaultUnit: 'can', defaultSize: '16oz' },
  { name: 'White Claw Surge Watermelon',   type: 'seltzer', defaultUnit: 'can', defaultSize: '16oz' },
  { name: 'White Claw Refrshr Iced Tea Lemon',     type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Refrshr Iced Tea Raspberry', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Refrshr Iced Tea Peach',     type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'White Claw Refrshr Iced Tea Mango',     type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Truly
  { name: 'Truly Wild Berry',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Lemonade',               type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Tropical',               type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Strawberry Lemonade',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Black Cherry',           type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Raspberry Lime',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Blueberry & Açaí',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Watermelon & Kiwi',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Peach',                  type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Pineapple',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Cranberry',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Truly Mango Chili',            type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // High Noon
  { name: 'High Noon Peach',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Watermelon',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Pineapple',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Black Cherry',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Grapefruit',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Lime',               type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Passion Fruit',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Mango',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Kiwi',               type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Blackberry',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Lemon',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Raspberry',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Blood Orange',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'High Noon Tangerine',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Bud Light Seltzer
  { name: 'Bud Light Seltzer Black Cherry',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Strawberry',        type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Mango',             type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Lemon Lime',        type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Peach',             type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Watermelon',        type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Pineapple',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Cranberry',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Iced Tea Lemon',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Iced Tea Cherry',   type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Iced Tea Peach',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Bud Light Seltzer Iced Tea Strawberry', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Corona Hard Seltzer
  { name: 'Corona Hard Seltzer Tropical Lime',   type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Corona Hard Seltzer Mango',           type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Corona Hard Seltzer Blackberry Lime', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Corona Hard Seltzer Strawberry',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Corona Hard Seltzer Passionfruit Lime', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Topo Chico Hard Seltzer
  { name: 'Topo Chico Hard Seltzer Tropical Mango',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Tangy Lemon Lime',  type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Strawberry Guava',  type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Piña Fresca',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Limon',             type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Strawberry Hibiscus', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Exotic Pineapple',   type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Oasis Cherry',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Topo Chico Hard Seltzer Prickly Pear',       type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Lone River Ranch Water
  { name: 'Lone River Ranch Water Original',      type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Lone River Ranch Water Grapefruit',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Lone River Ranch Water Lime',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Lone River Ranch Water Watermelon',    type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Lone River Ranch Water Mango',         type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Lone River Ranch Water Spicy Jalapeño', type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Vizzy Hard Seltzer
  { name: 'Vizzy Blueberry Pomegranate',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Pineapple Mango',                type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Strawberry Kiwi',                type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Black Cherry Lime',              type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Raspberry Lemonade',             type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Peach Orange',                   type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Watermelon Strawberry',          type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  { name: 'Vizzy Cranberry Lime',                 type: 'seltzer', defaultUnit: 'can', defaultSize: '12oz' },
  // Ciders
  { name: 'Angry Orchard Crisp Apple', type: 'cider', defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Angry Orchard Green Apple', type: 'cider', defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Angry Orchard Rosé',       type: 'cider', defaultUnit: 'can',    defaultSize: '12oz' },
  { name: 'Angry Orchard Stone Dry',  type: 'cider', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Strongbow Gold Apple',     type: 'cider', defaultUnit: 'can',    defaultSize: '14.9oz' },
  { name: 'Strongbow Honey & Apple',  type: 'cider', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Woodchuck Amber',          type: 'cider', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Woodchuck Granny Smith',   type: 'cider', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Crispin Original',         type: 'cider', defaultUnit: 'bottle', defaultSize: '12oz' },
  { name: 'Smith & Forge Hard Cider', type: 'cider', defaultUnit: 'can',    defaultSize: '16oz' },
  // Bourbon / American Whiskey
  { name: "Jack Daniel's Old No. 7",       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Jack Daniel's Tennessee Honey",  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Jack Daniel's Tennessee Fire",   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Jack Daniel's Tennessee Apple",  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jim Beam White',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jim Beam Black',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jim Beam Apple',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Wild Turkey 101',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Wild Turkey American Honey',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Maker's Mark",                   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Maker's Mark 46",                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Knob Creek Bourbon',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Knob Creek Rye',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Woodford Reserve',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Buffalo Trace',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bulleit Bourbon',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bulleit Rye',                    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Four Roses Bourbon',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Evan Williams Black',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Evan Williams Honey',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Elijah Craig Small Batch',       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Angel's Envy Bourbon",           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Old Forester 86",                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Larceny Bourbon',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Basil Hayden's",                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Booker's Bourbon",               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Eagle Rare 10 Year',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Michter's US*1 Bourbon",         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Heaven Hill Bourbon",            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Scotch Whisky
  { name: 'Johnnie Walker Red Label',       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Johnnie Walker Black Label',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Johnnie Walker Double Black',    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Johnnie Walker Blue Label',      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Glenfiddich 12 Year',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Glenfiddich 15 Year',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Macallan 12 Year Sherry Oak',    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Glenlivet 12 Year',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Glenlivet 15 Year',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Chivas Regal 12 Year',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Dewar's White Label",            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Famous Grouse',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Monkey Shoulder',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Irish Whiskey
  { name: 'Jameson Irish Whiskey',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jameson Caskmates IPA',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jameson Black Barrel',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Tullamore D.E.W.',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bushmills Original',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Redbreast 12 Year',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Canadian Whisky
  { name: 'Crown Royal Original',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Crown Royal Apple',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Crown Royal Peach',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Crown Royal Vanilla',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Seagram's 7 Crown",              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Canadian Club',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Japanese Whisky
  { name: 'Suntory Toki',                   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Nikka Coffey Grain',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Hibiki Japanese Harmony',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Vodka
  { name: 'Grey Goose',                     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Grey Goose La Poire',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Grey Goose L\'Orange',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Absolut Original',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Absolut Citron',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Absolut Raspberry',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Absolut Lime',                   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Absolut Peppar',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Belvedere',                      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Ketel One',                      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Ketel One Botanicals Grapefruit & Rose', type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Ketel One Botanicals Cucumber & Mint',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Tito's Handmade Vodka",          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Smirnoff No. 21',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Smirnoff Vanilla',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Smirnoff Raspberry',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Smirnoff Green Apple',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Smirnoff Watermelon',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Stolichnaya',                    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Cîroc',                          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Cîroc Red Berry',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Cîroc Pineapple',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'New Amsterdam Vodka',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'New Amsterdam Peach',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Svedka Original',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Skyy Vodka',                     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Deep Eddy Vodka',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Deep Eddy Lemon',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Deep Eddy Ruby Red',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Deep Eddy Peach',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'UV Vodka',                       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Pinnacle Vodka',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Burnett\'s Vodka',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Burnett\'s Strawberry Vodka',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Luksusowa Potato Vodka',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Rum
  { name: 'Bacardi Superior',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi Gold',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi Black',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi Coconut',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi Limón',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi Razz',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bacardi 151',                   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Captain Morgan Original Spiced', type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Captain Morgan Black Spiced',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Captain Morgan Coconut',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Captain Morgan Sliced Apple',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Malibu Original',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Malibu Mango',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Malibu Pineapple',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Kraken Black Spiced Rum',      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Myers's Dark Rum",             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Mount Gay Eclipse',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bumbu Original',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Don Q Cristal',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Appleton Estate Signature',  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Gosling's Black Seal",        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Sailor Jerry Spiced Rum',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Plantation 3 Stars',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Tequila
  { name: 'Patrón Silver',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Patrón Reposado',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Patrón Añejo',              type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Don Julio Blanco',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Don Julio Reposado',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Don Julio Añejo',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Don Julio 1942',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jose Cuervo Especial Silver', type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jose Cuervo Especial Gold',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Hornitos Plata',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Hornitos Reposado',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: '1800 Silver',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: '1800 Reposado',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: '1800 Añejo',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Espolòn Blanco',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Espolòn Reposado',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Casamigos Blanco',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Casamigos Reposado',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Casamigos Añejo',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'El Jimador Blanco',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'El Jimador Reposado',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Herradura Silver',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Herradura Reposado',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Cazadores Blanco',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Sauza Blue Silver',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Olmeca Altos Plata',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Clase Azul Reposado',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Teremana Blanco',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Teremana Reposado',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Mezcal
  { name: 'Del Maguey Vida',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Ilegal Joven Mezcal',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Monte Alban Mezcal',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Gin
  { name: 'Tanqueray London Dry',       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Tanqueray No. Ten',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Bombay Sapphire',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Hendrick's Gin",             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Beefeater London Dry',       type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Gordon's London Dry",        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Plymouth Gin',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Nolet's Silver Gin",         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Aviation American Gin',      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Monkey 47',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Botanist Islay Dry Gin',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Brandy / Cognac
  { name: 'Hennessy VS',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Hennessy VSOP',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Hennessy XO',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Rémy Martin VSOP',          type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Rémy Martin XO',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'E&J Brandy',                type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'E&J VSOP Brandy',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Courvoisier VS',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Courvoisier VSOP',           type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Martell VS',                 type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Paul Masson VSOP Brandy',    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Christian Brothers VS Brandy', type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  // Cordials / Liqueurs
  { name: 'Kahlúa Original',            type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: "Baileys Irish Cream",         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Fireball Cinnamon Whisky',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'RumChata',                    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Triple Sec',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Grand Marnier',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Cointreau',                   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Amaretto di Saronno',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'DeKuyper Peach Schnapps',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'DeKuyper Watermelon Pucker',  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Southern Comfort Original',   type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Jägermeister',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Midori Melon Liqueur',        type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'St. Germain Elderflower',     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Chambord Black Raspberry',    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Frangelico Hazelnut',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Drambuie',                    type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Limoncello',                  type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Aperol',                      type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Campari',                     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Sambuca',                     type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Schnapps Peppermint',         type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Blue Curaçao',               type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
  { name: 'Peach Schnapps',             type: 'liquor', defaultUnit: 'fifth', defaultSize: '750ml' },
]

export function searchProducts(query) {
  if (!query || query.trim().length < 1) return []
  const q = query.toLowerCase()
  return PRODUCTS.filter(p => p.name.toLowerCase().includes(q)).slice(0, 8)
}
