import { mergeConfig, defineConfig } from 'vitest/config'
import viteConfig from './vite.config.js'
import { loadTestEnv } from './scripts/loadTestEnv.js'

// DB-project tests need real local Supabase creds in both import.meta.env
// (src/lib/supabase.js) and process.env (tests/db/helpers/adminClient.js,
// which uses the service-role key — never VITE_-prefixed, since that'd
// expose it to the browser bundle). .env.test.local is generated by
// scripts/write-test-env.js from the running local stack, not committed.
export default mergeConfig(viteConfig, defineConfig({
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          environment: 'jsdom',
          include: ['src/**/*.test.js'],
          setupFiles: ['./tests/setup/vitestSetupUnit.js'],
          env: {
            VITE_SUPABASE_URL: 'http://localhost:54321',
            VITE_SUPABASE_ANON_KEY: 'unit-test-placeholder',
          },
        },
      },
      {
        extends: true,
        test: {
          name: 'db',
          environment: 'node',
          include: ['tests/db/**/*.test.js'],
          testTimeout: 15000,
          fileParallelism: true,
          env: loadTestEnv(),
        },
      },
    ],
  },
}))
