import { existsSync, readFileSync } from 'node:fs'

// Shared by vitest.config.js and playwright.config.js — both need the local
// Supabase creds from .env.test.local (generated by write-test-env.js) in
// plain process.env, since neither vitest.config.js nor playwright.config.js
// run through Vite's own import.meta.env loading.
export function loadTestEnv(path = '.env.test.local') {
  if (!existsSync(path)) return {}
  const contents = readFileSync(path, 'utf8')
  const env = {}
  for (const line of contents.split('\n')) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (match) env[match[1]] = match[2]
  }
  return env
}
